### ISSUE TITLE
dat not defined in AdaptiveStochastic

### ISSUE THREAD

**Issue by Sinansi** [flare9x/MarketCycles.jl#10]
In ehlers_cycle.jl, the first line below AdaptiveStochastic method signature declares variable x = dat in 

function AdaptiveStochastic(x::Array{Float64}; min_lag::Int64=1, max_lag::Int64=48,LPLength::Int64=10, HPLength::Int64=48, AvgLength::Int64=3)::Array{Float64}
    x = dat

when I invoke AdaptiveStochastic() I get the error:

**_ERROR: UndefVarError: dat not defined_**

I cant find what dat is referring to

**Comment by flare9x** [comment]
Try updating the package - it has since been rectified.

**Comment by Sinansi** [comment]
All good. Thank you so much!

**Comment by flare9x** [comment]
your welcome
