### ISSUE TITLE
Julia 1.2 Update

### ISSUE THREAD

**Issue by Sinansi** [flare9x/MarketCycles.jl#9]
Firstly, I would like thank you so much for the time and effort you spent to import Ehlers work to Julia.

I kindly ask you to upgrade the library to be compatible with Julia 1.2 when possible.

The following error is displayed with I try to install the library on Julia 1.2:
_julia> Pkg.add("MarketCycles")
ERROR: The following package names could not be resolved:
 * MarketCycles (not found in project, manifest or registry)
Please specify by known `name=uuid`._

Thank you!

**Comment by femtotrader** [comment]
Maybe this package could have more updates if it was moved to 
https://github.com/JuliaFinance or https://github.com/JuliaQuant
where a collective work could take place.

**Comment by flare9x** [comment]
```
]
add https://github.com/flare9x/MarketCycles.jl
```

**Comment by flare9x** [comment]
Working on registering this package.

**Comment by Sinansi** [comment]
Thank you so much Andrew. I have been checking this package almost everyday. Last installation attempt was yesterday.

**Comment by flare9x** [comment]
What happens when you try 

``` julia
]
add https://github.com/flare9x/MarketCycles.jl
```

**Comment by Sinansi** [comment]
I got the following compatibility error:

ERROR: Unsatisfiable requirements detected for package CSV [336ed68f]:
 CSV [336ed68f] log:
 ├─possible versions are: [0.3.0-0.3.1, 0.4.0-0.4.3, 0.5.0-0.5.21] or uninstalled
 ├─restricted to versions 0.5.21-0.5 by MarketCycles [5d10f61e], leaving only versions 0.5.21
 │ └─MarketCycles [5d10f61e] log:
 │   ├─possible versions are: 0.0.2 or uninstalled
 │   └─MarketCycles [5d10f61e] is fixed to version 0.0.2
 └─restricted to versions 0.5.18 by an explicit requirement — no versions left

**Comment by Sinansi** [comment]
I will update all the packages and let you know if installation succeed.

**Comment by Sinansi** [comment]
I will update all the packages and let you know if installation succeed.

**Comment by Sinansi** [comment]
Ok so after updating all packages, MarketCycles asked to downgrade DataFrames version from 0.20 to 0.18, so still some compatibility issues.

ERROR: Unsatisfiable requirements detected for package DataFrames [a93c6f00]:
 DataFrames [a93c6f00] log:
 ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0] or uninstalled
 ├─restricted to versions 0.18.0-0.18 by MarketCycles [ac9b3a88], leaving only versions 0.18.0-0.18.4
 │ └─MarketCycles [ac9b3a88] log:
 │   ├─possible versions are: 0.0.2 or uninstalled
 │   └─MarketCycles [ac9b3a88] is fixed to version 0.0.2
 └─restricted to versions 0.20.0 by an explicit requirement — no versions left

**Comment by flare9x** [comment]
Ok I changed the Project.toml file to include versions higher than what it was forcing: 

```julia
[compat]
julia = "^1.2"
DataFrames = ">= 0.18.0"
CSV = ">= 0.5.0"
```
This is the versioning from the build test: 

```julia
  Updating `~/build/flare9x/MarketCycles.jl/Project.toml`
  [336ed68f] + CSV v0.5.21
  [a93c6f00] + DataFrames v0.20.0
  [10745b16] + Statistics 
```

**Comment by Sinansi** [comment]
Awesome! I was able to install MarketCycles on Julia 1.2 

(v1.2) pkg> add https://github.com/flare9x/MarketCycles.jl
  Updating registry at `C:\Users\Sannan\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/flare9x/MarketCycles.jl`
  Updating git-repo `https://github.com/flare9x/MarketCycles.jl`
 Resolving package versions...
  Updating `C:\Users\Sannan\.julia\environments\v1.2\Project.toml`
  [ac9b3a88] + MarketCycles v0.0.2 #master (https://github.com/flare9x/MarketCycles.jl)
  Updating `C:\Users\Sannan\.julia\environments\v1.2\Manifest.toml`
  [ac9b3a88] + MarketCycles v0.0.2 #master (https://github.com/flare9x/MarketCycles.jl)

Thanks alot Andrew!

**Comment by flare9x** [comment]
Wonderful!
